name: 获取市场数据
on:
  push:
    branches:
      - main  # 当 main 分支有 push 事件时触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: ./data

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install axios node-fetch

    - name: Run getMarketData
      run: node getMarketData.js

    - name: Save output files
      run: |
        set -e
        mkdir -p ${{ env.OUTPUT_DIR }}
        if ls *_data.json 1> /dev/null 2>&1; then
          cp *_data.json ${{ env.OUTPUT_DIR }}
          echo "文件已成功复制到 ${{ env.OUTPUT_DIR }}"
        else
          echo "没有找到匹配的文件，跳过此步骤"
        fi
      if: always()  # 无论前面步骤是否出错，都会执行

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "actions"
        export TZ="Asia/Shanghai"
        git add ${{ env.OUTPUT_DIR }}/
        timestamp=$(date +"%Y-%m-%d %H:%M:%S")
        git commit -m "提交市场数据: $timestamp" || { echo "没有要提交的更改"; exit 0; }
        git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main || true  # 出错不停止
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main || true  # 出错不停止
